name: CI
on:
    push:
        branches:
        - main
    pull_request:
    schedule:
        - cron:  '17 3 * * 0'

jobs:
    flake8:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
        -
            uses: actions/setup-python@v4
            with:
                python-version: '3.x'
        -   name: "Main Script"
            run: |
                pip install flake8 flake8-quotes flake8-bugbear
                flake8 availability
    eslint:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v3
        -   uses: actions/setup-node@v3
        -
            run: |
                npm install
                npx eslint availability/static/availability.js



# vim: sw=4
