name: CI
on:
    push:
        branches:
        - main
    pull_request:
    schedule:
        - cron:  '17 3 * * 0'

jobs:
    python-lint:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4
        -
            uses: actions/setup-python@v5
            with:
                python-version: '3.x'
        -   name: Install uv
            uses: astral-sh/setup-uv@v5
        -   name: "Main Script"
            run: |
                uv run ruff check
                uv run mypy availability

    eslint:
        runs-on: ubuntu-latest
        steps:
        -   uses: actions/checkout@v4
        -   uses: actions/setup-node@v4
        -
            run: |
                npm install
                npx eslint availability/static/availability.js



# vim: sw=4
